import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/loginpatient">LoginPatient</Link>
        </li>
        <li>
          <Link to="/">LoginPatientOne</Link>
        </li>
        <li>
          <Link to="/createpatients">CreatePatients</Link>
        </li>
        <li>
          <Link to="/main">Main</Link>
        </li>
        <li>
          <Link to="/analysis">Analysis</Link>
        </li>
        <li>
          <Link to="/prescriptions">Prescriptions</Link>
        </li>
        <li>
          <Link to="/createprescription">CreatePrescription</Link>
        </li>
        <li>
          <Link to="/mainchat">MainChat</Link>
        </li>
        <li>
          <Link to="/createcheckup">CreateCheckUp</Link>
        </li>
        <li>
          <Link to="/createanalysis">CreateAnalysis</Link>
        </li>
        <li>
          <Link to="/mainone">MainOne</Link>
        </li>
        <li>
          <Link to="/analysisone">AnalysisOne</Link>
        </li>
        <li>
          <Link to="/prescriptionsone">PrescriptionsOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
